[package]
name = "hoary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
dioxus = "0.4.0"
dioxus-tui = "0.4.0"
opener = "0.6.1"
